// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.test.grpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.grpc.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 2;</code>
   * @return The realName.
   */
  String getRealName();
  /**
   * <code>string realName = 2;</code>
   * @return The bytes for realName.
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
