// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.test.grpc;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.grpc.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
